itemName = str(input("Enter food item name: \n"))
itemPrice = float(input("Enter item price: \n"))
itemQ = int(input("Enter item quantity: \n\n"))
print('RECEIPT')
print(f"{itemQ} {itemName} @ $ {itemPrice} = $ {itemQ * itemPrice}")
print(f"Total cost: $ {itemQ * itemPrice}\n\n")
item2 = str(input("Enter second food item name: \n"))
price2 = float(input("Enter item price: \n"))
q2 = int(input("Enter item quantity: \n\n"))
print('RECEIPT')
print(f"{itemQ} {itemName} @ $ {itemPrice} = $ {itemQ * itemPrice}")
print(f"{q2} {item2} @ $ {price2} = $ {q2 * price2}")
print(f"Total cost: $ {(itemQ * itemPrice) + (q2 * price2)}\n")
tot = (itemQ * itemPrice) + (q2 * price2)
grat = 0.15 * tot
print(f"15% gratuity: $ {grat}")
print(f"Total with tip: $ {tot + grat}")
